#ID del modelo del panel
id_modelo_panel: 10001
#Componentes respectivos a Thingsboard
thingsboard:
  device_token: YOUR_DEVICE_TOKEN
  host: YOUR_THINGSBOARD_HOST
  port: YOUR_THINGSBOARD_PORT
#Componentes respectivos a serial
serial:
  #Puerto correspondiente en el que se conectara el USB
  puerto: /dev/serial-adapter
#Componentes respectivos al control del relay del Test Alive
relay:
  pin: 8
  high_time: 1
  low_time: 60
#Componentes respectivos al control de la lectura de relays de los estados del panel
relay_monitor:
  alarm_pin: 13
  trouble_pin: 27
  publish_interval: 15
  alarm_active_high: true
  trouble_active_high: false
# Configuración del relay de silencio
silence_relay:
  pin: 22  # GPIO para el relay de silencio
  activation_time: 5  # Tiempo en segundos que el relay permanecerá activo
  active_high: true  # true si el relay se activa con señal HIGH, false para LOW
# Configuración del relay de reinicio
reset_relay:
  pin: 25  # GPIO para el relay de reinicio del panel
  activation_time: 5  # Tiempo en segundos que el relay permanecerá activo
  active_high: true  # true si el relay se activa con señal HIGH, false para LOW