#ID del modelo del panel
id_modelo_panel: 10001
#Componentes respectivos a Thingsboard
thingsboard:
  device_token: YOUR_DEVICE_TOKEN
  host: YOUR_THINGSBOARD_HOST
  port: YOUR_THINGSBOARD_PORT
#Componentes respectivos a serial
serial:
  #Puerto correspondiente en el que se conectara el USB
  puerto: /dev/serial-adapter
#Componentes respectivos al control del relay del Test Alive
relay:
  pin: 8
  high_time: 1
  low_time: 60
#Componentes respectivos al control de la lectura de relays de los estados del panel
relay_monitor:
  alarm_pin: 13
  trouble_pin: 27
  publish_interval: 15
  alarm_active_high: true
  trouble_active_high: false
